# =============================================================================
# main.tf — Provider configuration and backend
# =============================================================================
#
# Usage:
#   terraform init
#   terraform workspace new dev   # or staging / prod
#   terraform plan -var-file=environments/dev.tfvars
#   terraform apply -var-file=environments/dev.tfvars

terraform {
  required_version = ">= 1.7.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.40"
    }
  }

  # Remote state in S3 with DynamoDB locking.
  # bucket is supplied at init time via -backend-config so
  # that the account-specific name generated by bootstrap.sh does not need to be
  # hardcoded here. Run bootstrap.sh first — it prints the exact init command.
  backend "s3" {
    key             = "lambda-authorizer-service/terraform.tfstate"
    region          = "us-east-1"
    dynamodb_table  = "gridgrizzly-terraform-locks"
    encrypt         = true
  }
}

provider "aws" {
  region = var.aws_region

  shared_config_files      = ["~/.aws/conf"]

  default_tags {
    tags = {
      Project     = "lambda-authorizer-service"
      Environment = var.environment
      ManagedBy   = "terraform"
      Repository  = "lambda-authorizer-service"
    }
  }
}

# =============================================================================
# Data sources
# =============================================================================

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
